extraction:
  java:
    index:
      java_version: "9"
queries:
  - include: "*"
  - exclude: java/uncaught-number-format-exception
  - exclude: java/notify-instead-of-notify-all 
  - exclude: java/toctou-race-condition
