apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
  - name: "30092"
    port: 30092
    targetPort: 30092
    nodePort: 30092
  selector:
    io.kompose.service: kafka
  type: NodePort
status:
  loadBalancer: {}
