version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    labels:
      kompose.service.type: NodePort
    restart: always
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_autopurge.purgeInterval: "0"

  kafka:
    image: wurstmeister/kafka
    labels:
      kompose.service.type: NodePort
    restart: always
    ports:
      - "30092:30092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka.minikube"
      KAFKA_ADVERTISED_PORT: 30092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_PORT: 30092
